#!/usr/bin/env python

"""Plot an FDMNES dataset against the respective XANESNET output."""

from dataclasses import dataclass
from pathlib import Path
from typing import Final

import matplotlib.pyplot as plt
import numpy as np
from numpy.typing import NDArray
from yaml import safe_load

root: Final = Path(__file__).parent


@dataclass
class Config:
    """Input and output paths to be defined by configuration."""

    fdmnes: Path
    xanesnet: Path
    output: Path


@dataclass
class Spectrum:
    """A representation of a XANES spectrum."""

    energy: NDArray[np.float64]
    xanes: NDArray[np.float64]


def read_config(path: Path) -> Config:
    """Read configuration of input and output paths."""
    with path.open() as f:
        config = safe_load(f)
    return Config(**{k: root / v for k, v in config.items()})
        # root / config["fdmnes"],
        # root / config["xanesnet"],
        # root / config["output"],


def read_xanes(path: Path) -> Spectrum:
    """Read a XANES `.txt` file."""
    spectrum = np.loadtxt(path, skiprows=2)
    return Spectrum(spectrum[:, 0], spectrum[:, 1])


def plot_xanes(fdmnes: Path, xanesnet: Path, output: Path) -> None:
    """Compare XANES data from two folders via plots."""
    output.mkdir(parents=True)

    filenames = [path.name for path in fdmnes.glob("*.txt")]
    filenames.sort()

    for filename in filenames:
        f = read_xanes(fdmnes / filename)
        x = read_xanes(xanesnet / filename)

        fig, ax = plt.subplots()

        ax.plot(f.energy, f.xanes, label="FDMNES")
        ax.plot(x.energy, x.xanes, label="XANESNET")
        ax.set_title(filename)
        ax.legend()
        ax.grid()

        plot = output / f"{filename.replace('.txt', '')}.svg"
        fig.savefig(plot)
        plt.close(fig)


if __name__ == "__main__":
    config = read_config(root / "config.yaml")
    plot_xanes(**config.__dict__)
