#!/usr/bin/env python

# ruff: noqa: E731

"""Test input size against model accuracy for the `0.25_0.17_1` set."""

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from numpy.typing import NDArray


@dataclass
class Spectrum:
    """A representation of a XANES spectrum."""

    energy: NDArray[np.float64]
    xanes: NDArray[np.float64]


def read_xanes(path: Path) -> Spectrum:
    """Read a XANES `.txt` file."""
    spectrum = np.loadtxt(path, skiprows=2)
    return Spectrum(spectrum[:, 0], spectrum[:, 1])


def rmsd(basis: Path, predict: Path) -> np.float64:
    """Compute the RMSD of two directories."""
    walk = lambda x: {f.name for f in x.iterdir() if f.is_file()}
    xanes = lambda x: read_xanes(x).xanes
    rmsd_ = lambda b, p: np.sqrt(np.mean((xanes(b) - xanes(p)) ** 2))
    sect = sorted({(basis / f, predict / f) for f in walk(basis) & walk(predict)})
    return np.mean([rmsd_(b, p) for b, p in sect])


if __name__ == "__main__":
    root = Path(__file__).parent
    plot_xanes(
        root / "../../data/co_cl2_en2/cis/0.25_0.17_1/aggregate/conv",
        root / "../../gnn_std_xyz_001/xanes_pred",
        root / "plots",
    )
