dataset:
  type: xanesx
  root_path: data/fe/processed_train
  xyz_path: data/fe/xyz_train
  xanes_path: data/fe/xanes_train
#  params:
#    preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
#    fourier: False
#    fourier_concat: False

descriptors:
  - type: wacsf
    params:
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

model:
  type: aegan_mlp
  params:
    hidden_size: 256
    activation: prelu
    num_hidden_layers_gen: 2
    num_hidden_layers_shared: 2
    num_hidden_layers_dis: 2
  weight:
    kernel: xavier_uniform
    bias: zeros
    seed: 2025

hyperparams:
  batch_size: 16
  epochs: 100
  model_eval: False
  seed: 2021
  lr: [0.01, 0.00001]     #[generative autoencoder, discriminator]
  optim_fn: [Adam, Adam]
  loss: [mse, bce]
  loss_reg: [None, None]
  loss_lambda: [0.001, 0.001]

kfold: False
kfold_params:
  n_splits: 3
  n_repeats: 1
  seed: 2021

bootstrap: False
bootstrap_params:
  n_boot: 3
  n_size: 1.0
  weight_seed: [97, 39, 22]

ensemble: False
ensemble_params:
  n_ens: 3
  weight_seed: [97, 39, 22]

lr_scheduler: False
scheduler_params:
  type: step
  step_size: 10
  gamma: 0.5

standardscaler: False