dataset:
  type: xanesx
  root_path: data/fe
  xyz_path: data/fe/xyz_train
  xanes_path: data/fe/xanes_train
#  params:
#    preload: True                    # Preload dataset into RAM if True; otherwise load on-the-fly
#    fourier: False
#    fourier_concat: False

descriptor:
  - type: wacsf
    params:
      r_min: 1.0
      r_max: 6.0
      n_g2: 16
      n_g4: 32

model:
   type: lstm
   params:
     hidden_size: 100
     hidden_out_size: 50
     num_layers: 1
     dropout: 0.2
     activation: prelu
   weights:
     kernel: xavier_uniform
     bias: zeros
     seed: 2025

hyperparams:
  batch_size: 32
  lr: 0.001
  epochs: 50
  optimizer: Adam
  model_eval : False
  seed: 2021
  loss: mse
  loss_reg: L2 #None L1
  loss_lambda: 0.001

kfold: False
kfold_params:
  n_splits: 3
  n_repeats: 1
  seed: 2022

bootstrap: False
bootstrap_params:
  n_boot: 3
  n_size: 1.0
  weight_seed: [97, 39, 22]

ensemble: False
ensemble_params:
  n_ens: 3
  weight_seed: [97, 39, 22]

lr_scheduler: True
scheduler_params:
  type: step
  step_size: 100
  gamma: 0.5

standardscaler: False